### ISSUE TITLE
[Features] Console, offline/online indicator in server list screen, eggs install button, be able to see server files

### ISSUE THREAD

**Issue by Mathrious** [pterodactyl-app/Pterodactyl-app#11]
Console (Should be coming soon)
Circle graph to monitor both RAM and CPU usage
Offline/Online indicator in server list screen
Administrator Login
Eggs Install button
Be able to see server files, not necessarily upload anything yet but the ability to just be able to see them.

**Comment by rubentalstra** [comment]
what do you wanna see of the eggs please let me know here is the link of the api: 
https://deploys.io/docs/api/pterodactyl/v1/#get-eggs-in-nest
https://deploys.io/docs/api/pterodactyl/v1/#get-specific-egg

**Comment by Knight1** [comment]
The FileList returns an error, but the console crashes the App in iOS. Is the Console in Android already implemented?

**Comment by rubentalstra** [comment]
This app will not be maintenance because we are working on the official app.

**Comment by Knight1** [comment]
Link?
