### ISSUE TITLE
Add lang Indonesian

### ISSUE THREAD

**Issue by Chicadaa** [pterodactyl-app/Pterodactyl-app#80]
Can i request lang indonesian
Or i make lang for indonesian

**Comment by rubentalstra** [comment]
You can do it I’m not doing it then I’m using google translate and that’s not the point of this. I want to have native translators.

**Comment by YWatchman** [comment]
@Chicadaa are you willing to translate the app for the Indonesian language?

**Comment by faizalw3** [comment]
@YWatchman Hi, i am new to github. Maybe i can help you to translate the app for indonesian language as  a native people.

**Comment by ljavanbeek** [comment]
Yes you can translate the app to Indonesian @faizalw3 , just follow the instructions over here https://github.com/pterodactyl-app/Pterodactyl-app/blob/develop/CONTRIBUTING.md#add-language (you might want to use the English translation file instead of the text listed there)

**Comment by YWatchman** [comment]
Merged in #95
