### ISSUE TITLE
[Feature] Add a list of partners in the app

### ISSUE THREAD

**Issue by samjwalsh** [pterodactyl-app/Pterodactyl-app#86]
In the app, have a list of approved server hosts that you could click on and then login with your account details from that host instead of making an API key for each server.

You could also use this as an easy way to list every server you own from any approved host

**Comment by Rhydium** [comment]
Why would you even do that? There's nothing like an 'approved host'.

**Comment by samjwalsh** [comment]
> Why would you even do that? There's nothing like an 'approved host'.

bc i was talking to ruben on a discord and mentioned the idea and he told me to post it here so he didnt forget

**Comment by rubentalstra** [comment]
true.

**Comment by samjwalsh** [comment]
idk exactly what approved host means but deploys.io is affiliated with ptero in some way

**Comment by ZeProf2Code** [comment]
I think it's done.

**Comment by YWatchman** [comment]
Has been integrated with the latest release.
