### ISSUE TITLE
I cannot paste the API key[BUG]

### ISSUE THREAD

**Issue by Lukas562Dev** [pterodactyl-app/Pterodactyl-app#94]
i cannot paste the API key in the app.

I expected that i can paste it in.

 - Device: Honor7lite
 - Android Version 7

**Comment by rubentalstra** [comment]
Did you tried to long press on it and if it’s right then you will see a “paste” button. If not maybe you forget to copy the apikey

**Comment by Lukas562Dev** [comment]
omg  thank you

**Comment by Lukas562Dev** [comment]
Wait

**Comment by Lukas562Dev** [comment]
does not work

**Comment by Lukas562Dev** [comment]
it says that my key is forbidden or something

**Comment by rubentalstra** [comment]
Are you logging in the client panel “pterodactyl app” or the admin panel

**Comment by rubentalstra** [comment]
Probably your logging in to the admin panel. That’s the mistake

**Comment by Lukas562Dev** [comment]
what should i use?

**Comment by rubentalstra** [comment]
Client API key

**Comment by Lukas562Dev** [comment]
OMG

**Comment by Lukas562Dev** [comment]
pterodactyl app worked
thank you so much

**Comment by rubentalstra** [comment]
Your welcome can you please leave a better review behind if that’s possible 😊

**Comment by Lukas562Dev** [comment]
yes, ill go change it

**Comment by rubentalstra** [comment]
The console logs will be later.

**Comment by Lukas562Dev** [comment]
File manager coming soon, wow

**Comment by Lukas562Dev** [comment]
but why does like the file list message "this will be added soon" is like in iOS?

**Comment by rubentalstra** [comment]
No because we need to make a custom module for the pane for it and that cost time.

**Comment by Lukas562Dev** [comment]
ok

**Comment by YWatchman** [comment]
Module is within it's pre-alpha phase internally, waiting on frontend work to be done. :-)

**Comment by Lukas562Dev** [comment]
cool
